version: '3'

services:
  web:
    build: .
    command: gunicorn league_advisor_api.wsgi:application --bind 0.0.0.0:8000 --workers 4
    volumes:
      - .:/code
    ports:
      - 8000:8000
    env_file:
      - ./league_advisor_api/.env