# Generated by Django 4.0 on 2021-12-09 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_account_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='summoner_level',
            field=models.IntegerField(max_length=64),
        ),
    ]
