# Generated by Django 4.0 on 2021-12-09 23:33

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_account_summoner_champion_mastery_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='summoner_champion_mastery',
            field=models.JSONField(default=accounts.models.Account.contact_default),
        ),
        migrations.AlterField(
            model_name='account',
            name='summoner_level',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='account',
            name='summoner_match_history',
            field=models.JSONField(default=accounts.models.Account.contact_default),
        ),
    ]
