# Generated by Django 4.0 on 2021-12-10 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.IntegerField()),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField(default='')),
                ('plaintext', models.TextField(default='')),
                ('image', models.TextField(default='')),
                ('gold', models.IntegerField()),
                ('tags', models.TextField(default='')),
            ],
        ),
    ]
