# Generated by Django 4.0 on 2021-12-15 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField(default='')),
                ('plaintext', models.TextField(default='')),
                ('image', models.TextField(default='')),
                ('gold', models.IntegerField(default=0)),
                ('tags', models.TextField(default='')),
            ],
        ),
    ]
